# Generated by Django 4.2.1 on 2023-05-27 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conductor', models.CharField(max_length=100, unique=True)),
                ('edad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vehiculo', models.CharField(max_length=100, unique=True)),
                ('fecha_de_fabricacion', models.DateField()),
                ('patente', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_pasajero', models.CharField(max_length=100, unique=True)),
                ('inicio_viaje', models.DateTimeField()),
                ('fin_viaje', models.DateTimeField()),
                ('medidor_satisfecho', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
